spring.application.name=Eventos_Escolares

# Conexion a base de datos (Render)
spring.datasource.url=jdbc:postgresql://dpg-d5rluc6r433s738nvff0-a.frankfurt-postgres.render.com:5432/eventos_escolares
spring.datasource.username=user
spring.datasource.password=VXPgjRIknPUk6xcIzkL3J0dmNYNtD9Pu
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Hibernate y Errores
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never
server.error.include-message=always

# Configuracion de subida de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Localizacion de archivos estaticos
# Esto permite que Spring busque fotos en tu carpeta manual 'uploads'
spring.web.resources.static-locations=file:uploads/,classpath:/static/