spring.application.name=Eventos_Escolares

spring.datasource.url=jdbc:postgresql://dpg-d5rluc6r433s738nvff0-a.frankfurt-postgres.render.com:5432/eventos_escolares
spring.datasource.username=user
spring.datasource.password=VXPgjRIknPUk6xcIzkL3J0dmNYNtD9Pu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.error.include-stacktrace=never
server.error.include-message=always

# Subida de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=file:uploads/,classpath:/static/



