#spring.application.name=Eventos_Escolares
#
#spring.datasource.url=jdbc:mariadb://localhost:3307/eventos_escolares?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#server.error.include-stacktrace=never
#server.error.include-message=always


spring.application.name=Eventos_Escolares

spring.datasource.url=jdbc:postgresql://dpg-d5rluc6r433s738nvff0-a.frankfurt-postgres.render.com:5432/eventos_escolares
spring.datasource.username=user
spring.datasource.password=VXPgjRIknPUk6xcIzkL3J0dmNYNtD9Pu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.error.include-stacktrace=never
server.error.include-message=always
cloudinary.cloud-name=dw4gxw9pz
cloudinary.api-key=147632516461684
cloudinary.api-secret=sM-n4bd1C35K282aa5j4rROFB1I
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB





#spring.application.name=Eventos_Escolares
#
#spring.datasource.url=jdbc:postgresql://postgresql://user:VXPgjRIknPUk6xcIzkL3J0dmNYNtD9Pu@dpg-d5rluc6r433s738nvff0-a.frankfurt-postgres.render.com/eventos_escolares:5432/eventos_escolares
#spring.datasource.username=user
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#
#server.error.include-stacktrace=never
#server.error.include-message=always




